# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FilterDesignerWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FilterDesingerWidget(object):
    def setupUi(self, FilterDesingerWidget):
        FilterDesingerWidget.setObjectName("FilterDesingerWidget")
        FilterDesingerWidget.resize(400, 300)

        self.retranslateUi(FilterDesingerWidget)
        QtCore.QMetaObject.connectSlotsByName(FilterDesingerWidget)

    def retranslateUi(self, FilterDesingerWidget):
        _translate = QtCore.QCoreApplication.translate
        FilterDesingerWidget.setWindowTitle(_translate("FilterDesingerWidget", "Form"))
