# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/AudioFilterInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_AudioFilterInterface(object):
    def setupUi(self, AudioFilterInterface):
        AudioFilterInterface.setObjectName("AudioFilterInterface")
        AudioFilterInterface.resize(666, 475)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AudioFilterInterface.sizePolicy().hasHeightForWidth())
        AudioFilterInterface.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtWidgets.QHBoxLayout(AudioFilterInterface)
        self.horizontalLayout.setContentsMargins(20, 40, 20, 20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.SimpleCardWidget = SimpleCardWidget(AudioFilterInterface)
        self.SimpleCardWidget.setObjectName("SimpleCardWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.SimpleCardWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.StrongBodyLabel = StrongBodyLabel(self.SimpleCardWidget)
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.verticalLayout_3.addWidget(self.StrongBodyLabel)
        self.audiosTable = TableWidget(self.SimpleCardWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.audiosTable.sizePolicy().hasHeightForWidth())
        self.audiosTable.setSizePolicy(sizePolicy)
        self.audiosTable.setObjectName("audiosTable")
        self.audiosTable.setColumnCount(0)
        self.audiosTable.setRowCount(0)
        self.verticalLayout_3.addWidget(self.audiosTable)
        self.verticalLayout.addWidget(self.SimpleCardWidget)
        self.SimpleCardWidget_2 = SimpleCardWidget(AudioFilterInterface)
        self.SimpleCardWidget_2.setObjectName("SimpleCardWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.SimpleCardWidget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.StrongBodyLabel_2 = StrongBodyLabel(self.SimpleCardWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StrongBodyLabel_2.sizePolicy().hasHeightForWidth())
        self.StrongBodyLabel_2.setSizePolicy(sizePolicy)
        self.StrongBodyLabel_2.setObjectName("StrongBodyLabel_2")
        self.verticalLayout_4.addWidget(self.StrongBodyLabel_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_4.addLayout(self.formLayout)
        self.PrimaryPushButton = PrimaryPushButton(self.SimpleCardWidget_2)
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.verticalLayout_4.addWidget(self.PrimaryPushButton)
        self.verticalLayout.addWidget(self.SimpleCardWidget_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(AudioFilterInterface)
        QtCore.QMetaObject.connectSlotsByName(AudioFilterInterface)

    def retranslateUi(self, AudioFilterInterface):
        _translate = QtCore.QCoreApplication.translate
        AudioFilterInterface.setWindowTitle(_translate("AudioFilterInterface", "Form"))
        self.StrongBodyLabel.setText(_translate("AudioFilterInterface", "音频选择"))
        self.StrongBodyLabel_2.setText(_translate("AudioFilterInterface", "滤波器信息"))
        self.PrimaryPushButton.setText(_translate("AudioFilterInterface", "滤波"))
from qfluentwidgets import PrimaryPushButton, SimpleCardWidget, StrongBodyLabel, TableWidget
