# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/FIRFormInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_FIRFormInterface(object):
    def setupUi(self, FIRFormInterface):
        FIRFormInterface.setObjectName("FIRFormInterface")
        FIRFormInterface.resize(396, 291)
        self.formLayout = QtWidgets.QFormLayout(FIRFormInterface)
        self.formLayout.setObjectName("formLayout")
        self.BodyLabel_2 = BodyLabel(FIRFormInterface)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.BodyLabel_2)
        self.typesBox = ComboBox(FIRFormInterface)
        self.typesBox.setObjectName("typesBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.typesBox)
        self.BodyLabel_4 = BodyLabel(FIRFormInterface)
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.BodyLabel_4)
        self.lengthEdit = LineEdit(FIRFormInterface)
        self.lengthEdit.setObjectName("lengthEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lengthEdit)
        self.BodyLabel_3 = BodyLabel(FIRFormInterface)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.BodyLabel_3)
        self.BodyLabel = BodyLabel(FIRFormInterface)
        self.BodyLabel.setObjectName("BodyLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.BodyLabel)
        self.windowsBox = ComboBox(FIRFormInterface)
        self.windowsBox.setObjectName("windowsBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.windowsBox)
        self.LineEdit_2 = LineEdit(FIRFormInterface)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.LineEdit_2)

        self.retranslateUi(FIRFormInterface)
        QtCore.QMetaObject.connectSlotsByName(FIRFormInterface)

    def retranslateUi(self, FIRFormInterface):
        _translate = QtCore.QCoreApplication.translate
        FIRFormInterface.setWindowTitle(_translate("FIRFormInterface", "Form"))
        self.BodyLabel_2.setText(_translate("FIRFormInterface", "类型"))
        self.BodyLabel_4.setText(_translate("FIRFormInterface", "阶数"))
        self.BodyLabel_3.setText(_translate("FIRFormInterface", "截止频率"))
        self.BodyLabel.setText(_translate("FIRFormInterface", "窗函数"))


from qfluentwidgets import BodyLabel, ComboBox, LineEdit
