# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/FilterDesignerInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FilterDesignerInterface(object):
    def setupUi(self, FilterDesignerInterface):
        FilterDesignerInterface.setObjectName("FilterDesignerInterface")
        FilterDesignerInterface.resize(400, 300)
        self.TitleLabel = TitleLabel(FilterDesignerInterface)
        self.TitleLabel.setGeometry(QtCore.QRect(110, 90, 191, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TitleLabel.sizePolicy().hasHeightForWidth())
        self.TitleLabel.setSizePolicy(sizePolicy)
        self.TitleLabel.setObjectName("TitleLabel")

        self.retranslateUi(FilterDesignerInterface)
        QtCore.QMetaObject.connectSlotsByName(FilterDesignerInterface)

    def retranslateUi(self, FilterDesignerInterface):
        _translate = QtCore.QCoreApplication.translate
        FilterDesignerInterface.setWindowTitle(_translate("FilterDesignerInterface", "Form"))
        self.TitleLabel.setText(_translate("FilterDesignerInterface", "Filter Designer"))
from qfluentwidgets import TitleLabel
