# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/HomeInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomeInterface(object):
    def setupUi(self, HomeInterface):
        HomeInterface.setObjectName("HomeInterface")
        HomeInterface.resize(800, 600)
        HomeInterface.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout = QtWidgets.QVBoxLayout(HomeInterface)
        self.verticalLayout.setContentsMargins(20, 40, 20, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.LargeTitleLabel = LargeTitleLabel(HomeInterface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LargeTitleLabel.sizePolicy().hasHeightForWidth())
        self.LargeTitleLabel.setSizePolicy(sizePolicy)
        self.LargeTitleLabel.setObjectName("LargeTitleLabel")
        self.verticalLayout.addWidget(self.LargeTitleLabel, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.voiceAnalysisButton = TransparentPushButton(HomeInterface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voiceAnalysisButton.sizePolicy().hasHeightForWidth())
        self.voiceAnalysisButton.setSizePolicy(sizePolicy)
        self.voiceAnalysisButton.setObjectName("voiceAnalysisButton")
        self.horizontalLayout.addWidget(self.voiceAnalysisButton)
        self.filterDesignerButton = TransparentPushButton(HomeInterface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filterDesignerButton.sizePolicy().hasHeightForWidth())
        self.filterDesignerButton.setSizePolicy(sizePolicy)
        self.filterDesignerButton.setObjectName("filterDesignerButton")
        self.horizontalLayout.addWidget(self.filterDesignerButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)

        self.retranslateUi(HomeInterface)
        QtCore.QMetaObject.connectSlotsByName(HomeInterface)

    def retranslateUi(self, HomeInterface):
        _translate = QtCore.QCoreApplication.translate
        HomeInterface.setWindowTitle(_translate("HomeInterface", "Form"))
        self.LargeTitleLabel.setText(_translate("HomeInterface", "Getting Start!"))
        self.voiceAnalysisButton.setText(_translate("HomeInterface", "语音分析"))
        self.filterDesignerButton.setText(_translate("HomeInterface", "滤波器设计"))
from qfluentwidgets import LargeTitleLabel, TransparentPushButton
