# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/IIRFormInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore


class Ui_IIRFormInterface(object):
    def setupUi(self, IIRFormInterface):
        IIRFormInterface.setObjectName("IIRFormInterface")
        IIRFormInterface.resize(400, 300)

        self.retranslateUi(IIRFormInterface)
        QtCore.QMetaObject.connectSlotsByName(IIRFormInterface)

    def retranslateUi(self, IIRFormInterface):
        _translate = QtCore.QCoreApplication.translate
        IIRFormInterface.setWindowTitle(_translate("IIRFormInterface", "Form"))
