# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VoiceAnalysisInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VoiceAnalysisInterface(object):
    def setupUi(self, VoiceAnalysisInterface):
        VoiceAnalysisInterface.setObjectName("VoiceAnalysisInterface")
        VoiceAnalysisInterface.resize(712, 590)
        self.horizontalLayout = QtWidgets.QHBoxLayout(VoiceAnalysisInterface)
        self.horizontalLayout.setContentsMargins(20, 40, 20, 20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.TitleLabel = TitleLabel(VoiceAnalysisInterface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TitleLabel.sizePolicy().hasHeightForWidth())
        self.TitleLabel.setSizePolicy(sizePolicy)
        self.TitleLabel.setObjectName("TitleLabel")
        self.verticalLayout.addWidget(self.TitleLabel)
        self.SimpleCardWidget_3 = SimpleCardWidget(VoiceAnalysisInterface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SimpleCardWidget_3.sizePolicy().hasHeightForWidth())
        self.SimpleCardWidget_3.setSizePolicy(sizePolicy)
        self.SimpleCardWidget_3.setObjectName("SimpleCardWidget_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.SimpleCardWidget_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SubtitleLabel = SubtitleLabel(self.SimpleCardWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SubtitleLabel.sizePolicy().hasHeightForWidth())
        self.SubtitleLabel.setSizePolicy(sizePolicy)
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.horizontalLayout_2.addWidget(self.SubtitleLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.TransparentToolButton = TransparentToolButton(self.SimpleCardWidget_3)
        self.TransparentToolButton.setObjectName("TransparentToolButton")
        self.horizontalLayout_2.addWidget(self.TransparentToolButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.TableWidget = TableWidget(self.SimpleCardWidget_3)
        self.TableWidget.setObjectName("TableWidget")
        self.TableWidget.setColumnCount(0)
        self.TableWidget.setRowCount(0)
        self.verticalLayout_2.addWidget(self.TableWidget)
        self.verticalLayout.addWidget(self.SimpleCardWidget_3)
        self.SimpleCardWidget = SimpleCardWidget(VoiceAnalysisInterface)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SimpleCardWidget.sizePolicy().hasHeightForWidth())
        self.SimpleCardWidget.setSizePolicy(sizePolicy)
        self.SimpleCardWidget.setObjectName("SimpleCardWidget")
        self.verticalLayout.addWidget(self.SimpleCardWidget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.SimpleCardWidget_2 = SimpleCardWidget(VoiceAnalysisInterface)
        self.SimpleCardWidget_2.setObjectName("SimpleCardWidget_2")
        self.horizontalLayout.addWidget(self.SimpleCardWidget_2)

        self.retranslateUi(VoiceAnalysisInterface)
        QtCore.QMetaObject.connectSlotsByName(VoiceAnalysisInterface)

    def retranslateUi(self, VoiceAnalysisInterface):
        _translate = QtCore.QCoreApplication.translate
        VoiceAnalysisInterface.setWindowTitle(_translate("VoiceAnalysisInterface", "Form"))
        self.TitleLabel.setText(_translate("VoiceAnalysisInterface", "Voice Analysis"))
        self.SubtitleLabel.setText(_translate("VoiceAnalysisInterface", "文件列表"))
from qfluentwidgets import SimpleCardWidget, SubtitleLabel, TableWidget, TitleLabel, TransparentToolButton
