# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VoiceFilterInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VoiceFilterInterface(object):
    def setupUi(self, VoiceFilterInterface):
        VoiceFilterInterface.setObjectName("VoiceFilterInterface")
        VoiceFilterInterface.resize(492, 353)
        self.TitleLabel = TitleLabel(VoiceFilterInterface)
        self.TitleLabel.setGeometry(QtCore.QRect(110, 90, 191, 91))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TitleLabel.sizePolicy().hasHeightForWidth())
        self.TitleLabel.setSizePolicy(sizePolicy)
        self.TitleLabel.setObjectName("TitleLabel")

        self.retranslateUi(VoiceFilterInterface)
        QtCore.QMetaObject.connectSlotsByName(VoiceFilterInterface)

    def retranslateUi(self, VoiceFilterInterface):
        _translate = QtCore.QCoreApplication.translate
        VoiceFilterInterface.setWindowTitle(_translate("VoiceFilterInterface", "Form"))
        self.TitleLabel.setText(_translate("VoiceFilterInterface", "Voice Filter"))
from qfluentwidgets import TitleLabel
