# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/VoiceFilterInterface.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_VoiceFilterInterface(object):
    def setupUi(self, VoiceFilterInterface):
        VoiceFilterInterface.setObjectName("VoiceFilterInterface")
        VoiceFilterInterface.resize(666, 475)
        self.horizontalLayout = QtWidgets.QHBoxLayout(VoiceFilterInterface)
        self.horizontalLayout.setContentsMargins(20, 40, 20, 20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.SimpleCardWidget = SimpleCardWidget(VoiceFilterInterface)
        self.SimpleCardWidget.setObjectName("SimpleCardWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.SimpleCardWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.StrongBodyLabel = StrongBodyLabel(self.SimpleCardWidget)
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.verticalLayout_3.addWidget(self.StrongBodyLabel)
        self.voiceTable = TableWidget(self.SimpleCardWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.voiceTable.sizePolicy().hasHeightForWidth())
        self.voiceTable.setSizePolicy(sizePolicy)
        self.voiceTable.setObjectName("voiceTable")
        self.voiceTable.setColumnCount(0)
        self.voiceTable.setRowCount(0)
        self.verticalLayout_3.addWidget(self.voiceTable)
        self.verticalLayout.addWidget(self.SimpleCardWidget)
        self.SimpleCardWidget_2 = SimpleCardWidget(VoiceFilterInterface)
        self.SimpleCardWidget_2.setObjectName("SimpleCardWidget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.SimpleCardWidget_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.StrongBodyLabel_2 = StrongBodyLabel(self.SimpleCardWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StrongBodyLabel_2.sizePolicy().hasHeightForWidth())
        self.StrongBodyLabel_2.setSizePolicy(sizePolicy)
        self.StrongBodyLabel_2.setObjectName("StrongBodyLabel_2")
        self.verticalLayout_4.addWidget(self.StrongBodyLabel_2)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout_4.addLayout(self.formLayout)
        self.PrimaryPushButton = PrimaryPushButton(self.SimpleCardWidget_2)
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.verticalLayout_4.addWidget(self.PrimaryPushButton)
        self.verticalLayout.addWidget(self.SimpleCardWidget_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(VoiceFilterInterface)
        QtCore.QMetaObject.connectSlotsByName(VoiceFilterInterface)

    def retranslateUi(self, VoiceFilterInterface):
        _translate = QtCore.QCoreApplication.translate
        VoiceFilterInterface.setWindowTitle(_translate("VoiceFilterInterface", "Form"))
        self.StrongBodyLabel.setText(_translate("VoiceFilterInterface", "音频选择"))
        self.StrongBodyLabel_2.setText(_translate("VoiceFilterInterface", "滤波器信息"))
        self.PrimaryPushButton.setText(_translate("VoiceFilterInterface", "Primary push button"))


from qfluentwidgets import PrimaryPushButton, SimpleCardWidget, StrongBodyLabel, TableWidget
