# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VoiceWiget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VoiceWidget(object):
    def setupUi(self, VoiceWidget):
        VoiceWidget.setObjectName("VoiceWidget")
        VoiceWidget.resize(637, 534)

        self.retranslateUi(VoiceWidget)
        QtCore.QMetaObject.connectSlotsByName(VoiceWidget)

    def retranslateUi(self, VoiceWidget):
        _translate = QtCore.QCoreApplication.translate
        VoiceWidget.setWindowTitle(_translate("VoiceWidget", "Form"))
